
networks:
  face_cluster:
    driver: bridge

services:
  api-worker-1:
    image: face-recognition-api:latest
    container_name: face_rec-1
    volumes:
      - ${DATA_PATH}:/app/data
    networks:
      - face_cluster
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
      RESOURCES: ${RESOURCES}
    depends_on:
      - postgres_db
    expose:
      - 80

  api-worker-2:
    image: face-recognition-api:latest
    container_name: face_rec-2
    volumes:
      - ${DATA_PATH}:/app/data
    networks:
      - face_cluster
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
      RESOURCES: ${RESOURCES}
    depends_on:
      - postgres_db
    expose:
      - 80

  api-worker-3:
    image: face-recognition-api:latest
    container_name: face_rec-3
    volumes:
      - ${DATA_PATH}:/app/data
    networks:
      - face_cluster
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
      RESOURCES: ${RESOURCES}
    depends_on:
      - postgres_db
    expose:
      - 80

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - face_cluster

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - face_cluster
    expose:
      - 80
    depends_on:
      - api-worker-1
      - api-worker-2
      - api-worker-3
    volumes:
      - ${SSL_PATH}:/ssl
volumes:
  postgres_data: